### ISSUE TITLE
ERROR ITMS-90075 verify distribution build via app store

### ISSUE THREAD

**Issue by divinus** [tuarua/Swift-IOS-ANE#21]
After I added 'ios_dependencies/device' to my build, I can not upload the build to the appstore. the application loader produces this error:

ERROR ITMS-90075: "This bundle is invalid. The application-identifier entitlement is missing; it should contain your 10-character Apple Developer ID, followed by a dot, followed by your bundle identifier."

Without ios_dependencies build uploaded normally but for obvious reasons it does not launch.
Signing code is disabled in all targets in the xcode

i use air sdk 30, ios sdk 11.4, xcode 9.4. all other settings as in the tutorial

**Comment by tuarua** [comment]
Can you please provide more detail:

1. Did your ANE previously work with Xcode 9.3 or is this a brand new ANE you created after you upgraded to Xcode 9.4?
2. Confirm you are using latest AIR beta 30.0.0.103
3. Which IDE are you using to package?
4. Are you including any other 3rd party Dynamic Frameworks?

Can you validate your app using
/Applications/Xcode.app/Contents/Applications/Application\ Loader.app/Contents/Frameworks/ITunesSoftwareService.framework/Support/altool --validate-app -f /path/to/App.ipa -u [UN] -p [PW]

Run code sign and report back
codesign -dv Payload/SampleApp.app/Frameworks/SampleFramework.framework *

I am able to use Xcode 9.3, AIR Beta 30 and IntelliJ to successfully produce an app that passes verification

You are using 9.4 which is a different version of Swift, and may be the problem. It is explicitly stated in the README to use 9.3

**Comment by tuarua** [comment]
Closing due to lack of response.

**Comment by tuarua** [comment]
Issue is with adt.
When including Entitlements with your app adt is incorrectly applying Entitlements to the dynamic frameworks.
Investigating

**Comment by Borman2000** [comment]
That works
Thanks!
