### ISSUE TITLE
Support for iOS 12, Xcode 10, Swift 4.2

### ISSUE THREAD

**Issue by tuarua** [tuarua/Swift-IOS-ANE#23]
Support for iOS 12 will be added when AIR gets built with iOS SDK 12.
Although iOS 12 + Xcode 10 is due for release in late September, going by last year AIR 32 will be built with SDK 12.
Beta in mid November with release in December.

- Upgrade to Xcode 10.1
- Upgrade to iOS SDK 12.1
- Upgrade to Swift version 4.2.1 (swiftlang-1000.11.42 clang-1000.11.45.1)
- Upgraded to AIR SDK 32
- Add `FREArray.push()`
- Add `FREArray.insert()`
- Add `FREArray.remove()`
- Add `FREArray.isEmpty`
- Add `FREObject.hasOwnProperty()`
- Add `FREObject.toString()`
- Add `@dynamicMemberLookup` to `FreObjectSwift`. Adds cleaner way to extend FREObjects 
- Mark `FREObject.call()` as  `@discardableResult`
- Remove try catches and make better use of optionals
- Remove `ArgCountError` class
- Obsoleted `sendEvent()` method
- Deprecate `FREObject.setProp()` - use accessor or `FreSwiftObject` wrapper instead
- Deprecate `FREObject.getProp()` - use accessor or `FreSwiftObject` wrapper instead
- FreSwiftMainController.TAG is now `public static var String`
- UIColor / NSColor changed to single `convenience init()`
- Add `FreSwiftLogger` to trace any FREExceptions
- `FREObject.init()` to return optional and not require try
- CommonDependancies.ane renamed to FreSwift.ane
- Refactoring

Development underway in branch
https://github.com/tuarua/Swift-IOS-ANE/tree/3.0.0

**Comment by developerjackemail** [comment]
Hello, was this support for swift 4.2 already finished?

**Comment by tuarua** [comment]
No.
https://github.com/tuarua/Swift-IOS-ANE/milestone/4
