### ISSUE TITLE
native_extension/ane/build_xxx.sh script searches in wrong location

### ISSUE THREAD

**Issue by appearance** [tuarua/Swift-IOS-ANE#25]
The ANE build scripts, "native_extension/ane/build_xxx.sh", refers to location in Project_dir/Build/Platforms/... folders, where as, xcode 9.4.1 stores build files not in project folder. Can you explain what needs to be done to make your build_ios.sh script work without errors? 
UPDATING VIDEOS ON YOUTUBE REALLY HELPS USERS!
Thank you.

**Comment by tuarua** [comment]
Open Xcode > Preferences > Locations > Click Advanced...

<img width="799" alt="image" src="https://user-images.githubusercontent.com/12083217/46570717-d4db8600-c960-11e8-92fc-2cf2ee657f7c.png">
