### ISSUE TITLE
Anyway to cut down the size of ios dependencies frameworks? 

### ISSUE THREAD

**Issue by developerjackemail** [tuarua/Swift-IOS-ANE#26]
Hello, thanks for your great work first, I'm trying to follow them and learning, and I'm a new Swift Learner. Is there any way to cut down the size of ios dependencies frameworks? I test with your Vibration ANE example, and the IPA size goes to 42M, I use the old Admob ANE with Objective-c written test project, an empty project IPA only take less than 20M. Was adding all these huge 'dylib' necessary?

![image](https://user-images.githubusercontent.com/40427858/46746543-d6e77100-cce1-11e8-883c-c531fc992cac.png)

**Comment by developerjackemail** [comment]
And with distribution IPA version, the size goes to 70, on Vibration example project.

![image](https://user-images.githubusercontent.com/40427858/46747107-119dd900-cce3-11e8-94dc-57a2a7a9b277.png)

![image](https://user-images.githubusercontent.com/40427858/46747125-16628d00-cce3-11e8-98dc-416113c593cf.png)

**Comment by tuarua** [comment]
Don't confuse IPA size with the size of the final app in the App Store.
 
The size increase are the official Apple Swift libraries. If you build an iOS app with Swift in Xcode it produces an ipa with the same Swift files (which is most new apps now)
 
It's important to know that this doesn't mean a user who downloads the app from the app store downloads a file the same size as your ipa.
After you upload the ipa Apple compress/strip/thin the app
 
Apple say this 

> The size of libswiftCore.dylib in your IPA, and the size of your IPA in general, is somewhat meaningless these days. The new thinning features in the store will remove unnecessary content from your app when delivering to specific devices, and libswiftCore.dylib contains bitcode even if your app doesn't. This bitcode is removed before your app is downloaded to a customer device.

 https://stackoverflow.com/questions/41907323/what-is-the-file-size-overhead-of-the-bundled-swift-libraries-compared-to-an-obj

Please research before complaining.
