### ISSUE TITLE
Application Loader upload my ipa error.

### ISSUE THREAD

**Issue by 1395881288** [tuarua/Swift-IOS-ANE#27]
sorry,my english is poor
I have develop two app with one ane,
the first ipa ,Application Loader upload is ok,
the second ipa, Application Loader upload is error, this is the error message:

WARNING ITMS-90722: "Certificate Expired. The signing certificate "CN=Apple Worldwide Developer Relations Certification Authority, OU=Apple Worldwide Developer Relations, O=Apple Inc., C=US" with serial number 25 used to sign meeting.app/Frameworks/FreSwift.framework has expired. Learn more (https://help.apple.com/xcode/mac/current/#/dev154b28f09)."

**Comment by 1395881288** [comment]
when i change air28 to air30, it was right. thanks.

**Comment by tuarua** [comment]
This is a warning not an error.
It was resolved by Adobe in AIR 30
https://forums.adobe.com/thread/2495626
