### ISSUE TITLE
App Crashes on the device.

### ISSUE THREAD

**Issue by 1395881288** [tuarua/Swift-IOS-ANE#30]
I am very sorry my english was poor.
I have install those software to my macOS Mojave 10.14.2
Xcode 10.1 (10B61)
IntelliJ IDEA
AIR 32
and Copy the files from AIRSDK_patch into the corresponding folders in my AIR SDK.

I  install Hello World starter project  to my iphone6plus(10.3.1)
when I click the app,it crash.

last year I have success run the Hello World starter project in my iphone.

**Comment by tuarua** [comment]
Please confirm you have also downloaded and updated the ios_dependencies via get_ios_dependencies.sh.
Swift dylibs should be 4.2.1
FreSwift.framework should also be latest 3.0.0

<img width="1067" alt="image" src="https://user-images.githubusercontent.com/12083217/51089425-ae4d9800-1764-11e9-8ed4-e4c7565d3e2d.png">

**Comment by 1395881288** [comment]
I have downloaded and updated the ios_dependencies via get_ios_dependencies.sh.
Swift dylibs  4.2.1
FreSwift.framework  3.0.0
HelloWorldANE_FW.framework 1.0
this is the Main.ipa    http://witsbox-download.oss-cn-shanghai.aliyuncs.com/liugongtest/Main.ipa.zip

**Comment by 1395881288** [comment]
last year
I user the old  Swift-IOS-ANE version success run  on my iphone.

**Comment by tuarua** [comment]
I won't download random zips from due to safety.

To get the error that is causing the crash
In Xcode

- Open Window > Devices & Simulators
- Select your Device > View Device Logs
- Select the crash to view the problem.

Example
<img width="795" alt="image" src="https://user-images.githubusercontent.com/12083217/51203968-62345c00-18fa-11e9-8381-bb74f3e26280.png">

**Comment by 1395881288** [comment]
thanks.
<img width="1440" alt="2019-01-16 10 12 58" src="https://user-images.githubusercontent.com/24973451/51222233-cf3a0700-1977-11e9-909c-81640a018982.png">
[log.txt](https://github.com/tuarua/Swift-IOS-ANE/files/2762362/log.txt)

**Comment by 1395881288** [comment]
I Copy the files from AIRSDK_patch into the corresponding folders in my AIR32 SDK.
<img width="1384" alt="2019-01-16 7 03 01" src="https://user-images.githubusercontent.com/24973451/51245095-b1918f80-19c1-11e9-8782-053c6aaf6d52.png">

**Comment by tuarua** [comment]
Latest error:
Please see updated instructions.
https://github.com/tuarua/Swift-IOS-ANE#modifications-to-air-sdk

It seems ld64 **has** to be a symlink. Adobe will be fixing this soon I hope

The crash on device is due to signing error, which is why we need to replace adt.jar.

**Comment by 1395881288** [comment]
thank you very much,I don't have paypal. I'll donate your project later.

**Comment by 1395881288** [comment]
I have install the Hello World starter project to my iphone6plus(10.3.1)，it run very well.
![1](https://user-images.githubusercontent.com/24973451/51315273-c25b0780-1a8c-11e9-8bfd-90bec96f30c9.jpg)

**Comment by tuarua** [comment]
cool
