### ISSUE TITLE
code signature invalid for libswiftCore.dylib on ios 10.2

### ISSUE THREAD

**Issue by hooh** [tuarua/Swift-IOS-ANE#35]
Using FreSwift 4.1.0, Xcode 11.2.1 and Air 32, I got this error on ios 10.2.1 and ios 11 devices:

DYLD, Library not loaded: @rpath/libswiftCore.dylib | Referenced from: /private/var/containers/Bundle/Application/CEEBD220-AF50-480B-9DFE-73B287B2DAC3/ParentsApp.app/Frameworks/FreSwift.framework/FreSwift | Reason: no suitable image found.  Did find: | /private/var/containers/Bundle/Application/CEEBD220-AF50-480B-9DFE-73B287B2DAC3/ParentsApp.app/Frameworks/libswiftCore.dylib: code signature invalid for '/private/var/containers/Bundle/Application/CEEBD220-AF50-480B-9DFE-73B287B2DAC3/ParentsApp.app/Frameworks/libswiftCore.dylib' |  | /private/var/containers/Bundle/Application/CEEBD220-AF50-480B-9DFE-73B287B2DAC3/ParentsApp.app/Frameworks/libswiftCore.dylib: code signature invalid for '/private/var/containers/Bundle/Application/CEEBD220-AF50-480B-9DFE-73B287B2DAC3/ParentsApp.app/Frameworks/libswiftCore.dylib' 

It works on ios 13.3.1. Is the error related to using Air 32?

**Comment by tuarua** [comment]
> Is the error related to using Air 32?

Perhaps, It might depend what type of build you are created, eg debug, adhoc, app-store ?

This previous ticket mentions the exact same HelloMofilerExample.app
Are you the developer of this app or a user ?
https://github.com/tuarua/Swift-IOS-ANE/issues/28

**Comment by hooh** [comment]
I'm sorry for my quote of the log from #28 for convenience, and I have changed it to my log. I'm the developer of the app, which is built for In-House distribution. Can I fix the signature error?

**Comment by tuarua** [comment]
> which is built for In-House distribution.

What type of build did you create debug, adhoc, app-store ?
Please be more specific.

You may also need to open a ticket on https://github.com/Gamua/Adobe-Runtime-Support/issues
Adobe AIR adt does the signing, so is not something I can fix.

**Comment by hooh** [comment]
I use In-House distribution that allows companies to distribute apps internally something like adhoc.

**Comment by tuarua** [comment]
> something like adhoc.
What does that mean ? It's either ad-hoc or it's not.

How are you signing it. What provisioning profile are you using. How are you installing the app.
The error is related to code signature of the Apple libraries. It's nothing got to do with the FreSwift code.

If you don't provide specific details of what you are doing I can't help you.
You're basically dumping an error with little further info and telling me 'fix it'.

**Comment by hooh** [comment]
I'm using Enterprise Certificate and  In House Distribution. It's not Ad Hoc. And I'm signing it with the "In-House and Ad Hoc" certificate and installing it with the cable and Xcode.

These are my selection In the developer apple pages:

 Register a New Provisioning Profile
Distribution
    Ad Hoc
    tvOS Ad Hoc
    Developer ID
✓ In House
    tvOS In House

Create a New Certificate
Software
    Apple Development
    iOS App Development
    Mac Development
    Developer ID Installer
    Developer ID Application
    ✓In-House and Ad Hoc

**Comment by tuarua** [comment]
I have never used In House before (I don't do Enterprise)

> exporting app-store build

I would have thought you would export your ipa as an ad-hoc type if you are using _In-House and Ad Hoc_ certs

eg
-target ipa-ad-hoc
https://help.adobe.com/en_US/air/build/WS901d38e593cd1bac35eb7b4e12cddc5fbbb-8000.html

When you package an ipa for app-store the file structure is different - it creates a _swiftSupport_ folder containing libswiftCore.dylib et al which are **unsigned** as these get signed by Apple as part of the app store distribution. I am not familiar with how In-house distribution works.

iOS 13 includes these as system files which is probably why you only get this error on lower versions.

You will need to contact Harman or Apple for support/more details. I can't really help any further than what I have outlined above.
