### ISSUE TITLE
Error when trying to run sample app

### ISSUE THREAD

**Issue by kiwikanji** [tuarua/Swift-IOS-ANE#39]
as per the screen shot this is what I get when I try to run the sample app. Any ideas please as I'm really lost now.

<img width="827" alt="Screen Shot 2020-09-17 at 4 00 26 PM" src="https://user-images.githubusercontent.com/478200/93418784-3ce1c780-f8ff-11ea-90aa-779c32c294ff.png">

**Comment by tuarua** [comment]
If you are using the Simulator this is an open AIR bug
See https://github.com/Gamua/Adobe-Runtime-Support/issues/387

**Comment by tuarua** [comment]
This was fixed in AIR 33.1.1.406 + onwards
