### ISSUE TITLE
Basic Question about compiling

### ISSUE THREAD

**Issue by rodrigogermanlopez** [tuarua/Swift-IOS-ANE#4]
I'm not able to compile the XCode project, i changed the build settings to reflect my account, but as not much info / tutorials are available.
So, if any time u get a chance to make a video/tutorial about this, it would be amazing... I definitly want to get my hands dirty on Swift/AIR

**Comment by tuarua** [comment]
When you say not able to compile, do you get an error ?
Or is the ane not being created ?

**Comment by rodrigogermanlopez** [comment]
I'm talking about the XCode Porject itself... the .a file is "red" i can't open it... anyway, all the XCode exceeds my knowledge :P so I'm pretty sure I'm missing something.
Just wanna try to implement some functionality in Swift and compile the ANE. I'm just missing the workflow.

**Comment by tuarua** [comment]
The .a is the static library that is compiled when you build the project. It's not a file you open.
I understand your eagerness to try this stuff out but there are no shortcuts. You need to put in the time and effort to learn the basics of Xcode, what a static library is, what a framework is, building a simple iOS app etc. I don't mean to sound harsh.
I used https://www.udemy.com and https://www.raywenderlich.com/ when starting out with iOS development.

**Comment by rodrigogermanlopez** [comment]
Don't worry about it, no offense taken.  I'm saying that I'm not able to "Open in Finder" (open the location) of the .a file, cause apparently, it is not being generated. Although I have no errors.
Anyways, as I said before, this is just ignorance from my end and not a "repo" issue, you should definitely close the ticket.

**Comment by tuarua** [comment]
To build the .a and the frameworks Select the "SwiftIOSANE_LIB" target from the drop down and click Cmd+B to build the debug version
Then Cmd+Shift+I to build the release version.

**Comment by rodrigogermanlopez** [comment]
Thanks for the tip! I feel ashamed :D
Idk if using this as a "forum" is valid. I struggled with the default building path for XCode, that was why the compilation was failing, as it calls build_ios.sh and all the build folders were empty :)
Anyway, I managed to compile the ANE, i will start digging into it now.
Thanks for the help!

**Comment by tuarua** [comment]
np have fun digging

**Comment by rodrigogermanlopez** [comment]
Maybe another silly mistake, but I was able to run the project on the simulator, amazing job btw!!
But when testing on the device (device Run configuration) the app crashes automatically.
Here's the XCode Console log:
https://dl.dropboxusercontent.com/u/21621726/anelog.txt
