### ISSUE TITLE
Is there any way to create the ANE for Flashbuilder

### ISSUE THREAD

**Issue by ukmunnithan** [tuarua/Swift-IOS-ANE#41]
I am still using the Flash builder. Could you please share the script to generate the ANE.
I need to generate ANE by using swift language instead of Obj C. Please help.

**Comment by tuarua** [comment]
I don't use FlashBuilder
IntelliJ is marked as the pre-requisite IDE to follow the [starter projects](https://github.com/tuarua/Swift-IOS-ANE/tree/master/starter_projects) provided with the repo.

You can get a 30 day trial here
https://www.jetbrains.com/idea/download/#section=mac

Please don't open any more tickets asking for scripts, samples.
Don't send me any more unsolicited emails demanding I investigate your error logs.
