### ISSUE TITLE
App Crashes on the device.

### ISSUE THREAD

**Issue by rodrigogermanlopez** [tuarua/Swift-IOS-ANE#5]
Maybe a silly mistake, but I was able to run the project on the simulator, **Amazing job btw**!!
But when testing on the device ( iPhone ) ("device" Run configuration) the app crashes automatically.
[Here's the XCode Console log](https://dl.dropboxusercontent.com/u/21621726/anelog.txt)

**Comment by tuarua** [comment]
Please see the readme for notes on running on device
https://github.com/tuarua/Swift-IOS-ANE#running-on-device-

The ipa needs to be resigned for it to work. I built a tool to help with this.
Btw Adobe **are** working on an official way of building ANEs in Swift. 
Hopefully it will solve this step.
I don't know the ETA though.
