### ISSUE TITLE
Compile/Build error when use FREDispatchStatusEventAsync

### ISSUE THREAD

**Issue by MonkeyDoll** [tuarua/Swift-IOS-ANE#8]
I need to use async callback to Flex so i using 
`FREDispatchStatusEventAsync(ctx, "RESULT", "SUCCESS");`
But will result an error below
> "_FREDispatchStatusEventAsync", referenced from:

**Comment by tuarua** [comment]
Hello,
You can't call the FRE functions directly from Swift. That's what FlashRuntimeExtensions.swift handles. 
It bridges back to ObjectiveC

You call:
`sendEvent(ctx: context, name: "RESULT", value: "SUCCESS")`

where context is the FreContextSwift (which wraps FREContext)
https://github.com/tuarua/Swift-IOS-ANE/blob/master/native_library/ios/SwiftIOSANE/SwiftIOSANE_FW/SwiftController.swift#L20

**Comment by tuarua** [comment]
I've just added to example
https://github.com/tuarua/Swift-IOS-ANE/blob/master/native_library/ios/SwiftIOSANE/SwiftIOSANE_FW/SwiftController.swift#L58

**Comment by MonkeyDoll** [comment]
Oh, sorry for my mistake. I am able to compile now 
Thank you very much.

**Comment by tuarua** [comment]
No problem. I should have included in the example.
